version: "3.9"

services:
    act-dry-run:
        # tty: true
        build:
          context: ./
          dockerfile: dockerfile
        volumes:
            - ./:/home/act/SynthesizerVscript
        working_dir: /home/act/SynthesizerVscript
        command: act -n

    act-run:
        # tty: true
        build:
          context: ./
          dockerfile: dockerfile
        volumes:
            - ./:/home/act/SynthesizerVscript
        working_dir: /home/act/SynthesizerVscript
        command: act
